baseURL = 'https://gedankenpunkt.com/'
languageCode = 'de'
title = 'Gedankenpunkt.'
Copyright = 'Copyright © 2023 Michael Freimüller'
theme = 'arete'

[Params]
author = 'Michael Freimüller'
ShowThemeInfo = true
mainSections = ['meme','post']

[mediaTypes]
[mediaTypes.'application/rss+xml']
suffixes = ['xml']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true